global:
  scrape_interval: 1m
  scrape_timeout: 40s
  evaluation_interval: 1m
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 40s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: node
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 40s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9100
  file_sd_configs:
  - files:
    - /media/srv-dc01/edv/Gerrit/akk/prometheus/targets/*.json
    refresh_interval: 2m
    